# Generated by Django 4.2.2 on 2023-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusHire', '0005_jobopening_linkedin_jobopening_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password1', models.CharField(default='', max_length=100)),
                ('password2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
