# Generated by Django 4.2.2 on 2023-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusHire', '0002_student_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
