# Generated by Django 4.2.2 on 2023-08-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusHire', '0003_rename_user_student_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.CreateModel(
            name='Stud_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.IntegerField(default='')),
                ('skills', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=100)),
                ('internship', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=100)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
